seed: 42
device: cuda:0
num_steps_per_env: 40
max_iterations: 80000
empirical_normalization: false
policy:
  class_name: ActorCriticRecurrent
  init_noise_std: 0.9
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.01
  num_learning_epochs: 5
  num_mini_batches: 2
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.98
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1
save_interval: 100
experiment_name: unitree_go2_gsfix
run_name: ''
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: true
load_run: 2025-01-10_17-40-00
load_checkpoint: model_.*.pt
amp:
  hidden_dims:
  - 1024
  - 512
  learning_rate: 0.001
  file_path: ./exts/mpc_data/mpc_data_go2.npy
  gradient_penalty: 1
  reward_weight: 0.0
