asset_path: /home/yebj/code/go2_isaaclab/exts/scene_data/bj4_mesh_with_texture/blue/blue.obj
usd_dir: /home/yebj/code/go2_isaaclab/exts/scene_data/bj4_mesh_with_texture/blue
usd_file_name: blue.usd
force_usd_conversion: true
make_instanceable: false
mass_props:
  mass: 100.0
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props:
  collision_enabled: true
  contact_offset: null
  rest_offset: null
  torsional_patch_radius: null
  min_torsional_patch_radius: null
collision_approximation: convexDecomposition
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2025-01-12 at 20:38:28.
##
